version: '3'

services:
  concourse-db:
    image: postgres:9.6
    environment: # The values here should match the ones in application-local.yaml.
      POSTGRES_DB: trains
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"