spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: mysecretpassword
    url: jdbc:postgresql://localhost:5432/trains
  jpa:
    hibernate:
      ddl-auto: create